# Generated by Django 5.2.1 on 2025-05-31 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название экскурсии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание экскурсии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Экскурсия',
                'verbose_name_plural': 'Экскурсии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название точки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание точки')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядковый номер точки в экскурсии, начиная с 0.', verbose_name='Порядок в маршруте')),
                ('custom_image', models.ImageField(blank=True, help_text='Загрузите изображение для этой точки.', null=True, upload_to='poi_images/', verbose_name='Изображение точки')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='excursions.tour', verbose_name='Экскурсия')),
            ],
            options={
                'verbose_name': 'Точка интереса',
                'verbose_name_plural': 'Точки интереса',
                'ordering': ['tour', 'order'],
            },
        ),
    ]
